# Generated by Django 3.2.3 on 2022-03-06 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('c_email', models.EmailField(max_length=254)),
                ('c_phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_price', models.PositiveIntegerField()),
                ('f_name', models.CharField(max_length=20)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='food')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='food')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='food')),
                ('f_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='regions')),
                ('r_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_email', models.EmailField(max_length=254)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.region')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('expected_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.food')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_expiry', models.DateTimeField()),
                ('percentage', models.PositiveIntegerField(default=25)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.customer')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.region')),
            ],
        ),
        migrations.CreateModel(
            name='monthly_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.food')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('feed', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlfoods.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='c_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.region'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
