# Generated by Django 3.2.3 on 2022-03-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlfoods.food'),
        ),
    ]
