# Generated by Django 3.2.3 on 2022-03-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0002_alter_offers_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('recieved', 'recieved'), ('Delivery in progress', 'Delivery in progress')], max_length=50, null=True),
        ),
    ]
