# Generated by Django 3.2.3 on 2022-03-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0003_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('Delivery in progress', 'Delivery in progress')], max_length=50, null=True),
        ),
    ]
