# Generated by Django 3.2.3 on 2022-03-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0004_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
