# Generated by Django 3.2.3 on 2022-03-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0005_auto_20220328_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image_3',
        ),
    ]
