# Generated by Django 3.2.3 on 2022-03-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0006_auto_20220328_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
