# Generated by Django 3.2.3 on 2022-04-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0007_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('dormant', 'dormant')], default='active', max_length=20, null=True),
        ),
    ]
