# Generated by Django 3.2.3 on 2022-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0008_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_plan',
            name='shift',
            field=models.CharField(choices=[('morning', 'morning'), ('lunch', 'lunch'), ('evening', 'evening')], default='lunch', max_length=20),
        ),
        migrations.AddField(
            model_name='offers',
            name='pieces',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='shift',
            field=models.CharField(choices=[('morning', 'morning'), ('lunch', 'lunch'), ('evening', 'evening')], default='lunch', max_length=20),
        ),
    ]
