# Generated by Django 3.2.3 on 2022-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0010_orders_delivered_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food')),
            ],
        ),
    ]
