# Generated by Django 3.2.3 on 2022-05-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlfoods', '0011_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='blog', max_length=30),
            preserve_default=False,
        ),
    ]
